# Generated by Django 5.1.dev20240222031802 on 2024-02-22 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_model_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyEmptyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyOtherEmptyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "myemptymodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_model_app.myemptymodel",
                    ),
                ),
            ],
        ),
    ]
